# Generated by Django 4.0.2 on 2022-05-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_vaccination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='vaccination',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
