# Generated by Django 4.0.2 on 2022-05-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='vaccination',
            field=models.IntegerField(null=True),
        ),
    ]
