# Generated by Django 3.1.3 on 2022-05-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentVaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.PositiveIntegerField()),
                ('vaccinationDate', models.DateTimeField()),
                ('dosage', models.PositiveIntegerField(default=1)),
                ('vaccinationStatus', models.CharField(max_length=32)),
                ('vaccine', models.CharField(max_length=50)),
            ],
        ),
    ]
